import { createContext, useContext, useState, type ReactNode } from 'react';
import { ReaderIcon, BookmarkIcon, BookmarkFilledIcon, LightningBoltIcon, ArrowRightIcon, ArrowLeftIcon, BellIcon, CheckIcon, Cross2Icon } from '@radix-ui/react-icons';
import { FlowStack, MobileScroll, BottomSheet, KeyboardTextarea, useKeyboard, type FlowControls, type FlowScreen } from './mobile';
import dailyFeed from './data/daily-feed.json';
import dailyFables from './data/daily-fables.json';

type News = { id?:string; title:string; tag:string; desc:string; sourceName?:string; sourceUrl?:string; publishedAt?:string; why?:string };
const fallbackNews:News[] = [
{title:'从服装的细节，寻找新需求',tag:'欧洲 · 服装',desc:'从面料、剪裁与功能细节出发，观察消费者尚未被满足的日常需求。'},
{title:'AI工具如何进入设计工作流？',tag:'科技 · 全球',desc:'从图像生成到3D建模，哪些环节值得用真实项目来测试？'},
{title:'从小红书到TikTok：内容能跨市场吗？',tag:'内容与电商 · 中国 / 东南亚',desc:'同一类内容在不同平台、不同文化下，可能需要怎样的调整？'},
{title:'小空间里的收纳，有没有设计机会？',tag:'设计 · 日本',desc:'关注使用动作与空间约束，而不只关注产品外观。'},
{title:'独立服装品牌如何表达材质价值？',tag:'商业 · 欧洲',desc:'商品页的材料说明、触感表达和护理信息，能否帮助购买决策？'},
{title:'Amazon评论里，哪些问题反复出现？',tag:'电商 · 欧洲',desc:'按使用场景归类评论，比单看星级更容易发现具体问题。'},
{title:'韩国的穿搭内容，如何形成辨识度？',tag:'自媒体 · 韩国',desc:'比较视觉风格与实际搭配价值，区分审美偏好和购买需求。'},
{title:'东南亚消费者如何理解新品牌？',tag:'商业 · 东南亚',desc:'语言、气候和购物习惯不同，需要分国家观察。'},
{title:'淘宝的细分品类，能带来哪些问题线索？',tag:'电商 · 中国',desc:'看商品解决了什么问题，再判断其他市场是否也存在。'},
{title:'YouTube长内容如何讲清一个产品？',tag:'自媒体 · 全球',desc:'研究演示、对比与评论区追问，寻找消费者的信息缺口。'},
{title:'抖音的演示型内容，为什么容易被理解？',tag:'自媒体 · 中国',desc:'观察一个动作如何呈现使用前后的差别。'},
{title:'Instagram上的设计品牌如何建立风格？',tag:'设计 · 欧洲',desc:'分别观察产品、摄影与排版，避免把视觉热度当成销售表现。'},
{title:'炎热天气里的穿衣需求值得研究吗？',tag:'服装 · 东南亚',desc:'从透气、护理与通勤场景提出问题，再寻找用户证据。'},
{title:'日韩日用品，哪些细节可以被借鉴？',tag:'设计 · 日韩',desc:'把易用性、工艺与成本一起纳入比较。'},
{title:'跨市场发现机会，第一步要确认什么？',tag:'商业 · 中国 / 欧洲',desc:'确认同样的问题是否存在，以及谁愿意为解决它付费。'}
];
const news:News[] = dailyFeed.items?.length ? dailyFeed.items : fallbackNews;
const fableDateParts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(({type,value})=>[type,value]));
const fableDay=Math.floor(Date.UTC(Number(fableDateParts.year),Number(fableDateParts.month)-1,Number(fableDateParts.day))/86400000);
const dailyFable=dailyFables[(fableDay%dailyFables.length+dailyFables.length)%dailyFables.length];
const projects = [
{title:'为小众服装品牌，做更清楚的商品表达',category:'设计服务',region:'欧洲',lead:'把面料、版型和穿着场景，变成容易理解的商品页面。',customer:'拥有独立站、但缺少专职内容设计师的小型服装品牌。',revenue:'按单品收取图文设计费，或按月提供新品内容服务。价格与成本需要访谈后确定。',rivals:'待研究：当地电商摄影工作室、自由设计师，以及品牌内部制作团队。正式版应列出具体名称、服务、价格与来源。',risk:'客户是否愿意为内容改善单独付费？语言能力、拍摄资源和实际转化效果仍需确认。',first:'访谈3家小型服装品牌，了解商品内容的制作流程和最耗时的环节。'},
{title:'让设计师少做重复工作的素材整理工具',category:'轻量工具',region:'中国 / 欧洲',lead:'从命名、分类到交付，聚焦一个高频重复动作。',customer:'需要反复整理图片与交付文件的独立设计师、小型工作室。',revenue:'一次性模板销售，或按月提供工具服务；先确认使用频率再选择模式。',rivals:'待研究：现有素材管理软件、文件管理工具、团队自己制作的自动化脚本。',risk:'现有工具可能已经解决问题；需要证明新增工具能节省时间。',first:'记录自己一周的素材整理过程，再邀请3名设计师复现同一任务。'},
{title:'为跨市场产品，设计本地化内容样稿',category:'内容服务',region:'中国 / 东南亚',lead:'围绕一个产品，研究不同市场需要怎样的场景与表达。',customer:'准备测试新市场、但尚未组建本地内容团队的小型电商品牌。',revenue:'按市场和内容包收取制作费用；当地语言审核、拍摄成本单独核算。',rivals:'待研究：本地创意工作室、内容代理商和品牌合作的创作者。',risk:'不能仅靠翻译或热门模板；本地文化理解和效果归因是核心难点。',first:'选一个熟悉的品类，请目标市场的使用者评价两种不同表达。'}
];
const stages=['收藏','重点研究','准备优化','暂时搁置'];
type Saved={stage:string;note:string};
type Store={saved:Record<number,Saved>;setSaved:React.Dispatch<React.SetStateAction<Record<number,Saved>>>;read:number[];setRead:React.Dispatch<React.SetStateAction<number[]>>};
const Context=createContext<Store>(null!);
const useStore=()=>useContext(Context);
const feedStatus=dailyFeed.status;
const feedIsLive=feedStatus==='live'||feedStatus==='live-raw';
const feedLabel=feedStatus==='live'?'实时资讯':feedStatus==='live-raw'?'实时原文':'示例内容';
const demo=<span className={`demo ${feedIsLive?'live':''}`}>{feedLabel}</span>;
const dailyHero=typeof dailyFeed.heroImage==='string'&&dailyFeed.heroImage?dailyFeed.heroImage:'images/daily-hero-01.png';
const asset=(path:string)=>{const resolved=path.endsWith('editorial-hero.png')?dailyHero:path;return `${((import.meta as any).env?.BASE_URL||'/')}${resolved.replace(/^\//,'')}`};
const weekdayLabel=typeof dailyFeed.weekdayLabel==='string'&&dailyFeed.weekdayLabel?dailyFeed.weekdayLabel:new Intl.DateTimeFormat('zh-CN',{timeZone:'Europe/Rome',weekday:'long'}).format(new Date());
function DailyBanner(){return <div className="daily-banner"><img className="hero" src={asset('images/editorial-hero.png')} alt={`${weekdayLabel}日报主图`}/><div className="daily-banner-copy"><span>DAILY BRIEF</span><strong>{weekdayLabel}</strong></div></div>}
function DateBadge({onClick}:{onClick:()=>void}){const now=new Date();const date=new Intl.DateTimeFormat('sv-SE').format(now).replaceAll('-','.');const weekday=new Intl.DateTimeFormat('zh-CN',{weekday:'long'}).format(now);return <button className="date" onClick={onClick} aria-label="查看提醒安排"><b>{date}</b><span>{weekday} <BellIcon/></span></button>}
function PushSetup(){const [status,setStatus]=useState<'idle'|'working'|'done'|'missing'|'error'>('idle');const [message,setMessage]=useState('');const enable=async()=>{try{setStatus('working');const env=(import.meta as any).env||{};const apiUrl=String(env.VITE_PUSH_API_URL||'').replace(/\/$/,'');const vapidKey=String(env.VITE_VAPID_PUBLIC_KEY||'');if(!apiUrl||!vapidKey){setStatus('missing');setMessage('推送后端地址和 VAPID 公钥尚未配置');return}if(!('Notification' in window)||!('serviceWorker' in navigator)||!('PushManager' in window)){setStatus('error');setMessage('当前浏览器不支持 Web Push');return}const permission=await Notification.requestPermission();if(permission!=='granted'){setStatus('error');setMessage('你没有允许通知，之后仍可在这里重新开启');return}const registration=await navigator.serviceWorker.register(new URL('sw.js',document.baseURI));const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(vapidKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))});const response=await fetch(`${apiUrl}/subscribe`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subscription,timezone:'Europe/Rome',preferredTime:'07:40'})});if(!response.ok)throw new Error(`subscribe ${response.status}`);setStatus('done');setMessage('已开启工作日 07:40 通知');}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'通知开启失败')}};return <div className="push-setup"><div><strong>iPhone 通知</strong><small>{message||'开启后，日报更新时发送提醒'}</small></div><button className="secondary" onClick={enable} disabled={status==='working'}>{status==='done'?'已开启':status==='working'?'处理中…':'开启通知'}</button></div>}
const projectSteps=[
['访谈 3 家小型服装品牌，确认商品内容最耗时的环节。','整理 3 个当地内容服务竞品，比较交付方式和收费。','为 1 个单品做一页样稿，请品牌方评价是否更容易表达价值。'],
['记录自己和 3 名设计师一周的素材整理动作。','比较 3 个素材管理工具，找出仍然需要手工处理的步骤。','做一个只解决单一重复动作的原型，测量是否真的节省时间。'],
['选定 1 个品类，让中国、东南亚用户分别评价两种表达。','比较 3 个目标市场的本地内容团队与创作者案例。','制作一组本地化样稿，用小范围反馈确认哪些表达需要调整。'],
];
const projectForNews=(i:number)=>{const base=projects[i%projects.length];const steps=projectSteps[i%projectSteps.length];return {...base,first:steps.map((step,index)=>`${index+1}. ${step}`).join('  ')};};
function Toolbar({title,flow}:{title:string;flow:FlowControls}){return <div className="toolbar"><button aria-label="返回" onClick={flow.pop}><ArrowLeftIcon/></button><span>{title}</span><span className="small-brand">见闻</span></div>}
function Footer({active,flow}:{active:string;flow:FlowControls}){return <nav className="tabs" aria-label="主导航">{[['today','今日',ReaderIcon],['fable','寓言',BookmarkFilledIcon],['projects','项目',LightningBoltIcon],['saved','收藏',BookmarkIcon]].map(([id,label,Icon]:any)=><button key={id} aria-current={active===id?'page':undefined} onClick={()=>flow.replace(rootScreen(id))}><Icon/><span>{label}</span></button>)}</nav>}
function rootScreen(id:string):FlowScreen{return {id:'root',render:flow=><AppTabs initialTab={id} flow={flow}/>}}
function newsScreen(i:number):FlowScreen{return {id:`news-${i}`,headerHeight:48,header:flow=><Toolbar title={`今日精选 ${i+1} / 15`} flow={flow}/>,render:flow=><NewsDetail i={i} flow={flow}/>}}
function projectScreen(i:number):FlowScreen{return {id:`project-${i}`,headerHeight:48,header:flow=><Toolbar title="项目分析" flow={flow}/>,render:flow=><ProjectDetail i={i} flow={flow}/>}}
function AppTabs({initialTab,flow}:{initialTab:string;flow:FlowControls}){const [active,setActive]=useState(initialTab);const [direction,setDirection]=useState<'left'|'right'>('right');const tabOrder=['today','fable','projects','saved'];const switchTab=(next:string)=>{if(next===active)return;setDirection(tabOrder.indexOf(next)>tabOrder.indexOf(active)?'right':'left');setActive(next)};return <div className="tab-shell"><div className={`tab-scene slide-${direction}`} key={active}><Home kind={active} flow={flow}/></div><nav className="tabs" aria-label="主导航">{[['today','今日',ReaderIcon],['fable','寓言',BookmarkFilledIcon],['projects','项目',LightningBoltIcon],['saved','收藏',BookmarkIcon]].map(([id,label,Icon]:any)=><button key={id} aria-current={active===id?'page':undefined} onClick={()=>switchTab(id)}><Icon/><span>{label}</span></button>)}</nav></div>}

function HomeLegacy({kind,flow}:{kind:string;flow:FlowControls}){
const {saved,read}=useStore(); const [filter,setFilter]=useState('全部'); const [schedule,setSchedule]=useState(false);
return <><MobileScroll className="paper"><main className={`home ${kind}`}>
<header className="masthead"><div className="brand">见闻<span>DAILY<br/>BRIEF</span></div><button className="date" onClick={()=>setSchedule(true)} aria-label="查看提醒安排"><b>2026.09.21</b><span>星期一 <BellIcon/></span></button></header>
{kind==='today'?<><div className="intro"><h1>世界的新动向，<br/>你的下一步。</h1><div className="accent-rule"/><div className="edition"><span>15 条精选 · 约 10 分钟</span>{demo}</div></div><img className="hero" src={asset('images/editorial-hero.png')} alt="褶皱的白色织物流过拉丝金属表面"/><div className="stories">{news.slice(0,3).map((n,i)=><button className="story" key={n.title} onClick={()=>flow.push(newsScreen(i))}><span className="number">0{i+1}</span><div><div className="eyebrow">{n.tag}</div><h2>{n.title}</h2><p>{n.desc}</p></div></button>)}</div><button className="primary start" onClick={()=>flow.push(newsScreen(read.length<15?news.findIndex((_,i)=>!read.includes(i)):0))}>{read.length?`继续阅读 · 已读 ${read.length}/15`:'开始阅读'}<ArrowRightIcon/></button><p className="closing">好问题，带来新的可能。</p></>:
kind==='projects'?<><div className="page-heading"><div className="eyebrow">WEEKLY OPPORTUNITIES</div><h1>让见闻，<br/>变成可能。</h1><p>本周的 3 个项目方向，留给你慢慢判断。</p>{demo}<div className="notice">当前是分析结构演示，尚未接入真实资讯与竞品证据。</div></div>{projects.map((p,i)=><button className="project-row" key={p.title} onClick={()=>flow.push(projectScreen(i))}><div className="eyebrow">0{i+1} / {p.category} · {p.region}</div><h2>{p.title}</h2><p>{p.lead}</p><span className="text-action">查看完整分析 <ArrowRightIcon/></span>{saved[i]&&<small>已收藏 · {saved[i].stage}</small>}</button>)}<div className="schedule-inline"><BellIcon/>每周六 15:00 · 意大利时间</div></>:
<><div className="page-heading"><div className="eyebrow">YOUR COLLECTION</div><h1>值得留下的，<br/>再想深一点。</h1><p>{Object.keys(saved).length} 个收藏项目 · 分析与备注保存在本次原型会话</p></div><div className="filters" aria-label="收藏状态筛选">{['全部',...stages].map(s=><button key={s} className={s===filter?'selected':''} onClick={()=>setFilter(s)}>{s}</button>)}</div>{Object.entries(saved).filter(([,s])=>filter==='全部'||s.stage===filter).length?Object.entries(saved).filter(([,s])=>filter==='全部'||s.stage===filter).map(([key,s])=><button className="project-row" key={key} onClick={()=>flow.push(projectScreen(+key))}><div className="eyebrow">{s.stage} · {projects[+key].category}</div><h2>{projects[+key].title}</h2><p>{s.note||projects[+key].lead}</p><span className="text-action">查看分析与备注 <ArrowRightIcon/></span></button>):<div className="empty"><BookmarkIcon/><h2>{filter==='全部'?'给好想法，留一个位置。':'这个分类还没有项目'}</h2><p>去项目页读一读，遇到值得继续思考的方向，再点收藏。</p><button className="primary" onClick={()=>flow.replace(rootScreen('projects'))}>看看本周项目<ArrowRightIcon/></button></div>}</>}
</main></MobileScroll><BottomSheet open={schedule} onOpenChange={setSchedule} title="你的阅读节奏"><div className="sheet-body"><h3>工作日晨报</h3><p>周一至周五 · 07:40<br/>15条精选，约10分钟读完</p><h3>每周项目整理</h3><p>周六 · 15:00<br/>查看与筛选3–5个项目</p><p>时区：Europe/Rome，随夏令时调整。</p><div className="notice">这是通知安排预览。原型尚未接入 iPhone 推送，不会实际发送提醒。</div><button className="primary" onClick={()=>setSchedule(false)}>知道了<CheckIcon/></button></div></BottomSheet></>}
function SaveToggle({i,compact=false}:{i:number;compact?:boolean}){const {saved,setSaved}=useStore();const isSaved=Boolean(saved[i]);const toggle=()=>setSaved(v=>{const next={...v};if(next[i])delete next[i];else next[i]={stage:'收藏',note:''};return next});return <button className={`save-toggle ${compact?'compact':''} ${isSaved?'is-saved':''}`} aria-label={isSaved?'取消收藏':'收藏这条资讯'} onClick={toggle}>{isSaved?<BookmarkFilledIcon/>:<BookmarkIcon/>}<span>{isSaved?'已收藏':'收藏'}</span></button>}

function TodayHome({flow}:{flow:FlowControls}){const {read}=useStore();const start=read.length<15?news.findIndex((_,i)=>!read.includes(i)):0;return <><div className="intro"><h1>世界的新动向，<br/>你的下一步。</h1><div className="accent-rule"/><div className="edition"><span>15 条精选 · 约 10 分钟</span>{demo}</div><p className="reading-note">已读只记录浏览进度，是否收藏由你决定。</p></div><DailyBanner/><div className="stories">{news.slice(0,3).map((n,i)=><div className="story-row" key={n.title}><button className="story story-main" onClick={()=>flow.push(newsScreen(i))}><span className="number">0{i+1}</span><div><div className="eyebrow">{n.tag}</div><h2>{n.title}</h2><p>{n.desc}</p></div></button><SaveToggle i={i} compact/></div>)}</div><button className="primary start" onClick={()=>flow.push(newsScreen(start<0?0:start))}>{read.length?`继续浏览 · 已读 ${read.length}/15`:'开始浏览'}<ArrowRightIcon/></button><p className="closing">好问题，带来新的可能。</p></>}

function FableHome(){return <><div className="page-heading fable-heading"><div className="eyebrow">DAILY FABLE · {dailyFable.field}</div><h1>把一个概念，<br/>藏进一则故事。</h1><p>每天一个研究生水平的概念。先读寓言，再在结尾看见它的名字。</p><div className="fable-meta"><span>今天 · 每日一则</span><span>{dailyFable.keywords.join(' · ')}</span></div></div><article className="fable-card"><div className="fable-card-label">{dailyFable.field}</div><h2>{dailyFable.title}</h2>{dailyFable.story.map((paragraph,index)=><p className="fable-paragraph" key={index}>{paragraph}</p>)}<section className="fable-reveal"><div className="eyebrow">走到这里，才看见它</div><h3>{dailyFable.concept}</h3><p>{dailyFable.reveal}</p></section><section className="fable-explanation"><div className="eyebrow">正式解释</div><p>{dailyFable.explanation}</p></section><section className="fable-application"><div className="eyebrow">给今天的观察</div><p>{dailyFable.application}</p></section></article></>}

function WeeklyHome({flow}:{flow:FlowControls}){const {saved}=useStore();const selected=Object.entries(saved).filter(([,s])=>s.stage==='准备优化');return <><div className="page-heading"><div className="eyebrow">WEEKLY REVIEW</div><h1>从收藏里，<br/>选出要优化的。</h1><p>每周六 15:00，从你主动留下的资讯中选出值得继续研究的方向。</p>{demo}<div className="notice">这里只显示你在收藏夹里标记为「准备优化」的内容。已读不是进入本周项目的条件。</div></div>{selected.length?selected.map(([key,s],i)=>{const n=news[+key];return <button className="project-row" key={key} onClick={()=>flow.push(projectScreen(+key))}><div className="eyebrow">0{i+1} / {n.tag} · {s.stage}</div><h2>{n.title}</h2><p>{n.desc}</p><span className="text-action">查看项目分析 <ArrowRightIcon/></span></button>}):<div className="empty"><LightningBoltIcon/><h2>本周还没有要优化的项目</h2><p>{Object.keys(saved).length?`你已收藏 ${Object.keys(saved).length} 条资讯，去收藏夹把候选项移到「准备优化」。`:'先在今日里收藏值得留下的资讯，再到收藏夹筛选。'}</p><button className="primary" onClick={()=>flow.replace(rootScreen('saved'))}>去收藏夹筛选<ArrowRightIcon/></button></div>}<div className="schedule-inline"><BellIcon/>每周六 15:00 · 意大利时间</div></>}

function SavedHome({flow}:{flow:FlowControls}){const {saved}=useStore();const [filter,setFilter]=useState('全部');const entries=Object.entries(saved).filter(([,s])=>filter==='全部'||s.stage===filter);return <><div className="page-heading"><div className="eyebrow">YOUR COLLECTION</div><h1>你主动留下的，<br/>再想深一点。</h1><p>{Object.keys(saved).length} 条收藏资讯 · 阅读与收藏是两个独立动作</p></div><div className="filters" aria-label="收藏状态筛选">{['全部',...stages].map(s=><button key={s} className={s===filter?'selected':''} onClick={()=>setFilter(s)}>{s}</button>)}</div>{entries.length?entries.map(([key,s])=>{const n=news[+key];return <button className="project-row" key={key} onClick={()=>flow.push(projectScreen(+key))}><div className="eyebrow">{s.stage} · {n.tag}</div><h2>{n.title}</h2><p>{s.note||n.desc}</p><span className="text-action">查看分析并设置本周状态 <ArrowRightIcon/></span></button>}):<div className="empty"><BookmarkIcon/><h2>{filter==='全部'?'给好想法，留一个位置。':'这个分类还没有内容'}</h2><p>去今日浏览资讯，点击每篇文章里的「收藏这条资讯」。</p><button className="primary" onClick={()=>flow.replace(rootScreen('today'))}>回到今日<ArrowRightIcon/></button></div>}</>}

function Home({kind,flow}:{kind:string;flow:FlowControls}){const [schedule,setSchedule]=useState(false);return <><MobileScroll className="paper"><main className={`home ${kind}`}><header className="masthead"><div className="brand">见闻<span>DAILY<br/>BRIEF</span></div><DateBadge onClick={()=>setSchedule(true)}/></header>{kind==='today'?<TodayHome flow={flow}/>:kind==='fable'?<FableHome/>:kind==='projects'?<WeeklyHome flow={flow}/>:<SavedHome flow={flow}/>}</main></MobileScroll><BottomSheet open={schedule} onOpenChange={setSchedule} title="你的阅读节奏"><div className="sheet-body"><h3>工作日晨报</h3><p>周一至周五 · 07:40<br/>15条精选，约10分钟读完</p><h3>每周项目整理</h3><p>周六 · 15:00<br/>从收藏中选择准备优化的方向</p><p>时区：Europe/Rome，随夏令时调整。</p><PushSetup/><div className="notice">日报更新由 GitHub Actions 定时触发；iPhone 通知需要配置推送服务端。</div><button className="primary" onClick={()=>setSchedule(false)}>知道了<CheckIcon/></button></div></BottomSheet></>}

function NewsDetail({i,flow}:{i:number;flow:FlowControls}){const {read,setRead,saved}=useStore();const n=news[i];const published=n.publishedAt||new Intl.DateTimeFormat('sv-SE').format(new Date());return <MobileScroll className="paper"><article className="detail"><div className="eyebrow">{n.tag} · {published.replaceAll('-','.')}</div><h1>{n.title}</h1>{demo}<p className="lead">{n.desc}</p><div className="detail-save"><SaveToggle i={i}/><span>收藏由你决定，和已读进度无关。</span></div>{i===0&&<img className="detail-image" src={asset('images/editorial-hero.png')} alt="织物与金属材质"/>}<section><h2>先看清问题</h2><p>{feedIsLive?'这条摘要来自已配置的资讯源，先把事实、来源和你的判断分开，再决定是否收藏。':'这是一条用于体验阅读流程的观察题目。正式日报会在这里用简短摘要解释发生了什么，并给出可核验的来源。'}</p></section><section><h2>为什么值得关注</h2><p>{n.why||'把趋势转成具体问题：谁遇到了什么困难？现有办法有什么不足？这种需求是否持续存在？'}</p></section><section className="tinted"><h2>与你有什么关系</h2><p>可以从设计与使用体验出发，观察欧洲、中国、东南亚或日韩市场之间的差别。跨市场的适用性仍需实际验证。</p></section><section><h2>来源与判断</h2>{n.sourceUrl?<p><a href={n.sourceUrl} target="_blank" rel="noreferrer">{n.sourceName||'查看原文'}</a>{n.publishedAt?` · 发布于 ${n.publishedAt}`:''}。摘要与创业判断分开呈现。</p>:<p>示例内容 · 尚未接入实时新闻源。正式版会展示来源、发布时间及事实与推测的区分。</p>}</section><button className="primary" onClick={()=>{setRead(r=>r.includes(i)?r:[...r,i]);i<14?flow.replace(newsScreen(i+1)):flow.pop()}}>{i<14?'标记已读 · 下一条':'完成今日阅读'}<ArrowRightIcon/></button>{read.includes(i)&&<p className="saved-hint"><CheckIcon/>这条已经读过{saved[i]?' · 已收藏':''}</p>}</article></MobileScroll>}
function Block({title,children}:{title:string;children:ReactNode}){return <section><h2>{title}</h2><p>{children}</p></section>}
function ProjectDetailLegacy({i,flow}:{i:number;flow:FlowControls}){const {saved,setSaved}=useStore();const n=news[i];const p=projectForNews(i);const s=saved[i];const keyboard=useKeyboard();const [note,setNote]=useState(s?.note||'');const [status,setStatus]=useState(false);const [confirm,setConfirm]=useState(false);const [message,setMessage]=useState('');
const save=()=>{setSaved(v=>({...v,[i]:v[i]||{stage:'已收藏',note:''}}));setMessage('这条资讯已加入收藏，可在每周整理时继续筛选');};
return <><MobileScroll className="paper"><article className="detail"><div className="eyebrow">{p.category} · {p.region}</div><h1>{p.title}</h1>{demo}<p className="lead">{p.lead}</p><button className="primary" onClick={()=>s?setStatus(true):save()}>{s?<BookmarkFilledIcon/>:<BookmarkIcon/>}{s?`已收藏 · ${s.stage}`:'收藏完整分析'}</button>{message&&<p className="saved-hint" role="status">{message}</p>}<div className="notice">创业假设示例，尚无已核验的市场证据。收藏用于后续筛选，不代表建议投入资金。</div><Block title="01 / 项目与需求假设">{p.lead} 需要通过用户访谈确认问题是否存在、出现频率及付费意愿。</Block><Block title="02 / 目标客户">{p.customer}</Block><Block title="03 / 竞品研究">{p.rivals}</Block><Block title="04 / 盈利方式">{p.revenue}</Block><Block title="05 / 与你的匹配">设计能力可以用于原型、信息表达和用户研究。在意大利便于观察当地场景，但市场知识、客户资源和语言要求需要逐项确认。</Block><Block title="06 / 风险与待验证问题">{p.risk}</Block><Block title="证据记录">演示版本 · 2026.09.21。正式版将保存资讯来源、竞品链接、分析日期与收藏时的版本，更新时单独标注。</Block>{s&&<section className="notes"><h2>我的筛选与备注</h2><button className="stage-button" onClick={()=>setStatus(true)}>{s.stage}<ArrowRightIcon/></button><label htmlFor="project-note">记录你想进一步确认的事</label><KeyboardTextarea id="project-note" value={note} onChange={e=>setNote(e.target.value)} onBlur={()=>keyboard.hide()} placeholder="例如：先了解客户现在如何解决这个问题…"/><button className="secondary" onClick={()=>{keyboard.hide();setSaved(v=>({...v,[i]:{...v[i],note}}));setMessage('备注已保存')}}>保存备注<CheckIcon/></button>{s.stage==='准备验证'&&<div className="tinted"><h3>建议的第一步</h3><p>{p.first}</p><small>仅显示下一步建议，尚未创建执行任务。</small></div>}<button className="remove" onClick={()=>setConfirm(true)}>移出收藏夹</button></section>}<button className="text-action" onClick={()=>flow.pop()}><ArrowLeftIcon/>返回继续筛选</button></article></MobileScroll><BottomSheet open={status} onOpenChange={setStatus} title="这个项目，下一步呢？"><div className="sheet-body">{stages.map(stage=><button className="stage-option" key={stage} onClick={()=>{setSaved(v=>({...v,[i]:{...v[i],stage}}));setStatus(false);setMessage(`已移至「${stage}」`)}}>{stage}{s?.stage===stage?<CheckIcon/>:<ArrowRightIcon/>}</button>)}</div></BottomSheet><BottomSheet open={confirm} onOpenChange={setConfirm} title="移出收藏夹？"><div className="sheet-body"><p>这份项目的备注与筛选状态会一并移除，项目仍可在每周项目中找到。</p><button className="primary" onClick={()=>{setSaved(v=>{const next={...v};delete next[i];return next});setConfirm(false);setNote('');setMessage('已移出收藏')}}>移出收藏<Cross2Icon/></button><button className="secondary" onClick={()=>setConfirm(false)}>保留收藏</button></div></BottomSheet></>}
function ProjectDetail({i,flow}:{i:number;flow:FlowControls}){const {saved,setSaved}=useStore();const n=news[i];const p=projectForNews(i);const s=saved[i];const keyboard=useKeyboard();const [note,setNote]=useState(s?.note||'');const [status,setStatus]=useState(false);const [confirm,setConfirm]=useState(false);const [message,setMessage]=useState('');const save=()=>{setSaved(v=>({...v,[i]:v[i]||{stage:'已收藏',note:''}}));setMessage('这条资讯已加入收藏，可在每周整理时继续筛选')};return <><MobileScroll className="paper"><article className="detail"><div className="eyebrow">{n.tag} · 项目方向</div><h1>{n.title}</h1>{demo}<p className="lead">{n.desc}</p><button className="primary" onClick={()=>s?setStatus(true):save()}>{s?<BookmarkFilledIcon/>:<BookmarkIcon/>}{s?`已收藏 · ${s.stage}`:'收藏这条资讯'}</button>{message&&<p className="saved-hint" role="status">{message}</p>}<div className="notice">这条资讯先作为收藏保存；只有在每周整理中标记为「准备优化」，才会进入项目页。下面的客户、竞品和盈利方式是待验证的分析结构。</div><Block title="01 / 可能形成的项目">{p.lead} 需要通过用户访谈确认问题是否存在、出现频率及付费意愿。</Block><Block title="02 / 目标客户">{p.customer}</Block><Block title="03 / 竞品研究">{p.rivals}</Block><Block title="04 / 盈利方式">{p.revenue}</Block><Block title="05 / 与你的匹配">设计能力可以用于原型、信息表达和用户研究。在意大利便于观察当地场景，但市场知识、客户资源和语言要求需要逐项确认。</Block><Block title="06 / 风险与待验证问题">{p.risk}</Block><Block title="证据记录">演示版本 · 2026.09.21。正式版将保存资讯来源、竞品链接、分析日期与收藏时的版本，更新时单独标注。</Block>{s&&<section className="notes"><h2>我的每周筛选</h2><button className="stage-button" onClick={()=>setStatus(true)}>{s.stage}<ArrowRightIcon/></button><label htmlFor="project-note">记录你想进一步确认的事</label><KeyboardTextarea id="project-note" value={note} onChange={e=>setNote(e.target.value)} onBlur={()=>keyboard.hide()} placeholder="例如：先了解客户现在如何解决这个问题…"/><button className="secondary" onClick={()=>{keyboard.hide();setSaved(v=>({...v,[i]:{...v[i],note}}));setMessage('备注已保存')}}>保存备注<CheckIcon/></button>{s.stage==='准备优化'&&<div className="tinted"><h3>建议的第一步</h3><p>{p.first}</p><small>仅显示下一步建议，尚未创建执行任务。</small></div>}<button className="remove" onClick={()=>setConfirm(true)}>移出收藏夹</button></section>}<button className="text-action" onClick={()=>flow.pop()}><ArrowLeftIcon/>返回继续筛选</button></article></MobileScroll><BottomSheet open={status} onOpenChange={setStatus} title="设置每周筛选状态"><div className="sheet-body"><p>只有选择「准备优化」的收藏资讯，才会出现在项目页。</p>{stages.map(stage=><button className="stage-option" key={stage} onClick={()=>{setSaved(v=>({...v,[i]:{...v[i],stage}}));setStatus(false);setMessage(`已移至「${stage}」`)}}>{stage}{s?.stage===stage?<CheckIcon/>:<ArrowRightIcon/>}</button>)}</div></BottomSheet><BottomSheet open={confirm} onOpenChange={setConfirm} title="移出收藏夹？"><div className="sheet-body"><p>这条资讯会从收藏中移除，也不会出现在本周项目里。</p><button className="primary" onClick={()=>{setSaved(v=>{const next={...v};delete next[i];return next});setConfirm(false);setNote('');setMessage('已移出收藏')}}>移出收藏<Cross2Icon/></button><button className="secondary" onClick={()=>setConfirm(false)}>保留收藏</button></div></BottomSheet></>}

export default function Prototype(){const [saved,setSaved]=useState<Record<number,Saved>>({});const [read,setRead]=useState<number[]>([]);return <Context.Provider value={{saved,setSaved,read,setRead}}><div className="jianwen"><FlowStack initial={rootScreen('today')}/></div></Context.Provider>}
